Document: dhcpsnoopingd-fem
Title: Debian dhcpsnoopingd-fem Manual
Author: <insert document author here>
Abstract: This manual describes what dhcpsnoopingd-fem is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dhcpsnoopingd-fem/dhcpsnoopingd-fem.sgml.gz

Format: postscript
Files: /usr/share/doc/dhcpsnoopingd-fem/dhcpsnoopingd-fem.ps.gz

Format: text
Files: /usr/share/doc/dhcpsnoopingd-fem/dhcpsnoopingd-fem.text.gz

Format: HTML
Index: /usr/share/doc/dhcpsnoopingd-fem/html/index.html
Files: /usr/share/doc/dhcpsnoopingd-fem/html/*.html
